# Builder
FROM python:3.11-slim AS builder

WORKDIR /install

COPY requirements.txt .
RUN pip install --prefix=/install -r requirements.txt

# Runtime
FROM python:3.11-slim

WORKDIR /app

COPY --from=builder /install /usr/local
COPY . .

EXPOSE 5000

CMD ["python", "app.py"]