apiVersion: v1
kind: Service
metadata:
  name: private-app-service
spec:
  type: NodePort
  selector:
    app: private-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
