- name: Update and install packages
  hosts: all
  become: yes
  vars_files:
    - vault.yml
  tasks:
    - name: Update apt
      include_tasks: dist_update_upgrade.yml
    - name: Install docker 
      include_tasks: docker_install.yml
    - name: Install containerd and configure 
      include_tasks: containerd_install.yml
    - name: Install kubernetes
      include_tasks: kube_install.yml
